### ISSUE TITLE
可以提供易快报的接口一键使用么，一个个添加效率好低

### ISSUE THREAD

**Issue by huixisheng** [ekuaibao/open-platform-docs#4]
![image](https://user-images.githubusercontent.com/1518967/198771232-f23e3c88-754d-4c88-90c7-89c17384a638.png)

**Comment by DogeFeng** [comment]
https://hose2019.feishu.cn/drive/folder/fldcnQiqSXImHLrjL0Kld4Gutgg
可以在这个链接里下载接口postman的导入文件，这是之前一次培训时对外分享的。

**Comment by 911061873** [comment]
+1，我最近正在整理接口，等我有空弄好了我提交PR
